" Remove compatiblity with Vi
set nocompatible
filetype off

" Allow text to be removed in insert mode
set backspace=2

" Tabs that appear 4 spaces wide
set tabstop=4

" Indents of only one tab
set shiftwidth=4

" ==PLUGINS==
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Plugins goes there.
Plugin 'gmarik/Vundle.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-syntastic/syntastic'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()
filetype plugin indent on


" Add lines
set number

" Enable syntax highlighting
syntax on

" Cool colors
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=52
colorscheme slate

" Lightline color scheme
let g:lightline = {
      \ 'colorscheme': 'seoul256',
      \ }

" == NERDTree ==

" Open NERDTree on file opening
" and go to previous (last accessed) window.
function! OpenNERDTree()
	NERDTree
	vertical resize 32
	wincmd p
endfunction

augroup NERDTree_conf
	autocmd!
	autocmd VimEnter * call OpenNERDTree()
	"Close NERDTree if it is the last active buffer
	autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
augroup END

let g:NERDTreeShowHidden=1

" == Syntaxtic ==
let g:syntastic_c_compiler = 'gcc'
let g:syntastic_c_compiler_options = '-Wall -Werror -Wextra'
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_c_check_header = 1
let g:syntastic_c_remove_include_errors = 1

" The Gray Colomn of Death
set cc=80
highlight ColorColumn ctermbg=8 ctermfg=7
highlight Comment ctermfg=8

highlight LineNr ctermfg=7 ctermbg=8
highlight Visual ctermfg=7
highlight NonText ctermfg=8

highlight NERDTreeUp ctermfg=2
highlight NERDTreeDir ctermfg=2
highlight NERDTreeDirSlash ctermfg=2
highlight NERDTreeHelp ctermfg=8

highlight VertSplit ctermfg=0
highlight SignColomn ctermfg=0
set fillchars+=vert:\ 

set cursorline
highlight CursorLineNR ctermbg=7

" Show tabs
set list
set listchars=tab:⇢-
highlight SpecialKey ctermfg=8

" Enable mouse
set mouse=a

" ==MAPPINGS==

let mapleader = "-"

" Toggle NERDTree
nnoremap <leader>n :NERDTreeToggle<cr>
" Open .vimrc in a separate tab
nnoremap <leader>ev :tabedit<cr>:e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Save and quit
nnoremap <c-s> :w<cr>
nnoremap <c-q> :wq<cr>
nnoremap <leader><c-q> :q!<cr>

" Tab utils
nnoremap <tab><Up> :tabedit<cr>:call OpenNERDTree()<cr>
nnoremap <s-tab><Up> :tabedit<cr>
nnoremap <tab><Right> :tabnext<cr>
nnoremap <tab><Left> :tabprevious<cr>
nnoremap <tab><Down> :q<cr>

" Duplicate line
inoremap <c-d> <esc>yypi
nnoremap <c-d> yyp

" Uppercase word
nnoremap <c-u> veU<esc>
inoremap <c-u> <esc>veU<esc>i

" alt + *
nnoremap ¨ veu<esc>

" Quoting
nnoremap <leader>" lbi"<esc>ea"<esc>
nnoremap <leader>' lbi'<esc>ea'<esc>
vnoremap <leader>" <esc>a"<esc>'<i"<esc>
vnoremap <leader>' <esc>a'<esc>'<i'<esc>

" Auto-indent .c & .h files
function! s:autoindent()
	let l:pos = getpos(".")
	normal! gg=G
	call setpos('.', l:pos)
endfunction

augroup autoIndent
	autocmd!
	autocmd BufWritePre,BufRead *.[ch] call s:autoindent()
augroup END

" Comment generation
nnoremap <leader>c 0i#<esc>0
augroup comments
	autocmd!
	autocmd BufRead *.[ch] nnoremap <buffer> <leader>c 0i/*<esc>$a*/<esc>0
	autocmd BufRead *.cpp nnoremap <buffer> <leader>c 0i//<esc>0
	autocmd BufRead *.vim nnoremap <buffer> <leader>c 0i"<esc>0
augroup END

" Better tab completion
set wildmode=longest,list,full
set wildmenu

" Auto C-style header creation
function! s:cheader()
	let l:headername = toupper(substitute(expand("%:t"), "[.]", "_", ""))

	call append(0, '#endif')
	call append(0, "")
	call append(0, '# define ' . l:headername)
	call append(0, '#ifndef ' . l:headername)
	MexicanHeader
	normal Gddk
endfunction

" Create command
command! CHeader call s:cheader()
nnoremap <buffer> <leader>h :CHeader<cr>

" == RUSH ==

" Pair creation
inoremap ( ()<esc>i
inoremap [ []<esc>i
inoremap { {}<esc>i

" 42 Header
source $HOME/.vim/header.vim

" Extra Whitespace
augroup whitespacehl
	autocmd!	
	autocmd Syntax * match ExtraWhitespace / \{2,}/
augroup END

" Move swap files to .vim
set directory=$HOME/.vim//
